### ISSUE TITLE
Assignment 1 Q Learning does not converge to correct solution

### ISSUE THREAD

**Issue by magnusja** [CalciferZh/cs234#1]
Hey there,

your Q-Learning code does not converge to the correct solution. It is always going left in state 0. I have the exact same problem with my implementation. 
Do you have any hints?

Thanks,
Magnus

**Comment by CalciferZh** [comment]
Since the frozen lake is slippery, you won't always go left even though your action is "go left". At state 0, whichever action you take, you have a probability of 2/3 to stay at state 0, and a prob of 1/3 to go to state 4. So the learning algorithm simply takes the first action. You can `print(env.P)` to see the details.   
In my test, my trained robot can always walk to state 15.
Hope this can help you.

**Comment by magnusja** [comment]
All right, I guess that makes sense. I will take some time and think that though.

Thanks a lot!
